FROM mcr.microsoft.com/devcontainers/javascript-node:1-20-bullseye

# FROM node:20-alpine3.17

# RUN apk update && apk add git

# RUN set -ex && apk --no-cache add sudo

# RUN sudo npm i -g pm2

# USER node

# CMD npm start